// Code generated by goctl. DO NOT EDIT.
// Source: oms.proto

package omsclient

import (
	"context"

	"SimplePick-Mall-Server/service/oms/rpc/oms"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CartAddReq             = oms.CartAddReq
	CartAddResp            = oms.CartAddResp
	CartDeleteReq          = oms.CartDeleteReq
	CartDeleteResp         = oms.CartDeleteResp
	CartListData           = oms.CartListData
	CartListReq            = oms.CartListReq
	CartListResp           = oms.CartListResp
	CartUpdateReq          = oms.CartUpdateReq
	CartUpdateResp         = oms.CartUpdateResp
	OrderAddReq            = oms.OrderAddReq
	OrderAddResp           = oms.OrderAddResp
	OrderDeleteReq         = oms.OrderDeleteReq
	OrderDeleteResp        = oms.OrderDeleteResp
	OrderInfoReq           = oms.OrderInfoReq
	OrderInfoResp          = oms.OrderInfoResp
	OrderListData          = oms.OrderListData
	OrderListReq           = oms.OrderListReq
	OrderListResp          = oms.OrderListResp
	OrderUpdateReq         = oms.OrderUpdateReq
	OrderUpdateResp        = oms.OrderUpdateResp
	ReturnApplyAddReq      = oms.ReturnApplyAddReq
	ReturnApplyAddResp     = oms.ReturnApplyAddResp
	ReturnApplyDeleteReq   = oms.ReturnApplyDeleteReq
	ReturnApplyDeleteResp  = oms.ReturnApplyDeleteResp
	ReturnApplyListData    = oms.ReturnApplyListData
	ReturnApplyListReq     = oms.ReturnApplyListReq
	ReturnApplyListResp    = oms.ReturnApplyListResp
	ReturnApplyUpdateReq   = oms.ReturnApplyUpdateReq
	ReturnApplyUpdateResp  = oms.ReturnApplyUpdateResp
	ReturnReasonAddReq     = oms.ReturnReasonAddReq
	ReturnReasonAddResp    = oms.ReturnReasonAddResp
	ReturnReasonDeleteReq  = oms.ReturnReasonDeleteReq
	ReturnReasonDeleteResp = oms.ReturnReasonDeleteResp
	ReturnReasonListData   = oms.ReturnReasonListData
	ReturnReasonListReq    = oms.ReturnReasonListReq
	ReturnReasonListResp   = oms.ReturnReasonListResp
	ReturnReasonUpdateReq  = oms.ReturnReasonUpdateReq
	ReturnReasonUpdateResp = oms.ReturnReasonUpdateResp
	Skus                   = oms.Skus

	Oms interface {
		// 添加订单
		OrderAdd(ctx context.Context, in *OrderAddReq, opts ...grpc.CallOption) (*OrderAddResp, error)
		// 订单列表
		OrderList(ctx context.Context, in *OrderListReq, opts ...grpc.CallOption) (*OrderListResp, error)
		// 更新订单
		OrderUpdate(ctx context.Context, in *OrderUpdateReq, opts ...grpc.CallOption) (*OrderUpdateResp, error)
		// 删除订单
		OrderDelete(ctx context.Context, in *OrderDeleteReq, opts ...grpc.CallOption) (*OrderDeleteResp, error)
		// 订单详情
		OrderInfo(ctx context.Context, in *OrderInfoReq, opts ...grpc.CallOption) (*OrderInfoResp, error)
		// 添加退货原因
		ReturnReasonAdd(ctx context.Context, in *ReturnReasonAddReq, opts ...grpc.CallOption) (*ReturnReasonAddResp, error)
		// 更新退货原因
		ReturnReasonUpdate(ctx context.Context, in *ReturnReasonUpdateReq, opts ...grpc.CallOption) (*ReturnReasonUpdateResp, error)
		// 退货原因列表
		ReturnReasonList(ctx context.Context, in *ReturnReasonListReq, opts ...grpc.CallOption) (*ReturnReasonListResp, error)
		// 删除退货原因
		ReturnReasonDelete(ctx context.Context, in *ReturnReasonDeleteReq, opts ...grpc.CallOption) (*ReturnReasonDeleteResp, error)
		// 添加退货
		ReturnApplyAdd(ctx context.Context, in *ReturnApplyAddReq, opts ...grpc.CallOption) (*ReturnApplyAddResp, error)
		// 更新退货
		ReturnApplyUpdate(ctx context.Context, in *ReturnApplyUpdateReq, opts ...grpc.CallOption) (*ReturnApplyUpdateResp, error)
		// 退货列表
		ReturnApplyList(ctx context.Context, in *ReturnApplyListReq, opts ...grpc.CallOption) (*ReturnApplyListResp, error)
		// 删除退货
		ReturnApplyDelete(ctx context.Context, in *ReturnApplyDeleteReq, opts ...grpc.CallOption) (*ReturnApplyDeleteResp, error)
		// 添加购物车
		CartAdd(ctx context.Context, in *CartAddReq, opts ...grpc.CallOption) (*CartAddResp, error)
		// 更新购物车
		CartUpdate(ctx context.Context, in *CartUpdateReq, opts ...grpc.CallOption) (*CartUpdateResp, error)
		// 购物车列表
		CartList(ctx context.Context, in *CartListReq, opts ...grpc.CallOption) (*CartListResp, error)
		// 删除购物车
		CartDelete(ctx context.Context, in *CartDeleteReq, opts ...grpc.CallOption) (*CartDeleteResp, error)
	}

	defaultOms struct {
		cli zrpc.Client
	}
)

func NewOms(cli zrpc.Client) Oms {
	return &defaultOms{
		cli: cli,
	}
}

// 添加订单
func (m *defaultOms) OrderAdd(ctx context.Context, in *OrderAddReq, opts ...grpc.CallOption) (*OrderAddResp, error) {
	client := oms.NewOmsClient(m.cli.Conn())
	return client.OrderAdd(ctx, in, opts...)
}

// 订单列表
func (m *defaultOms) OrderList(ctx context.Context, in *OrderListReq, opts ...grpc.CallOption) (*OrderListResp, error) {
	client := oms.NewOmsClient(m.cli.Conn())
	return client.OrderList(ctx, in, opts...)
}

// 更新订单
func (m *defaultOms) OrderUpdate(ctx context.Context, in *OrderUpdateReq, opts ...grpc.CallOption) (*OrderUpdateResp, error) {
	client := oms.NewOmsClient(m.cli.Conn())
	return client.OrderUpdate(ctx, in, opts...)
}

// 删除订单
func (m *defaultOms) OrderDelete(ctx context.Context, in *OrderDeleteReq, opts ...grpc.CallOption) (*OrderDeleteResp, error) {
	client := oms.NewOmsClient(m.cli.Conn())
	return client.OrderDelete(ctx, in, opts...)
}

// 订单详情
func (m *defaultOms) OrderInfo(ctx context.Context, in *OrderInfoReq, opts ...grpc.CallOption) (*OrderInfoResp, error) {
	client := oms.NewOmsClient(m.cli.Conn())
	return client.OrderInfo(ctx, in, opts...)
}

// 添加退货原因
func (m *defaultOms) ReturnReasonAdd(ctx context.Context, in *ReturnReasonAddReq, opts ...grpc.CallOption) (*ReturnReasonAddResp, error) {
	client := oms.NewOmsClient(m.cli.Conn())
	return client.ReturnReasonAdd(ctx, in, opts...)
}

// 更新退货原因
func (m *defaultOms) ReturnReasonUpdate(ctx context.Context, in *ReturnReasonUpdateReq, opts ...grpc.CallOption) (*ReturnReasonUpdateResp, error) {
	client := oms.NewOmsClient(m.cli.Conn())
	return client.ReturnReasonUpdate(ctx, in, opts...)
}

// 退货原因列表
func (m *defaultOms) ReturnReasonList(ctx context.Context, in *ReturnReasonListReq, opts ...grpc.CallOption) (*ReturnReasonListResp, error) {
	client := oms.NewOmsClient(m.cli.Conn())
	return client.ReturnReasonList(ctx, in, opts...)
}

// 删除退货原因
func (m *defaultOms) ReturnReasonDelete(ctx context.Context, in *ReturnReasonDeleteReq, opts ...grpc.CallOption) (*ReturnReasonDeleteResp, error) {
	client := oms.NewOmsClient(m.cli.Conn())
	return client.ReturnReasonDelete(ctx, in, opts...)
}

// 添加退货
func (m *defaultOms) ReturnApplyAdd(ctx context.Context, in *ReturnApplyAddReq, opts ...grpc.CallOption) (*ReturnApplyAddResp, error) {
	client := oms.NewOmsClient(m.cli.Conn())
	return client.ReturnApplyAdd(ctx, in, opts...)
}

// 更新退货
func (m *defaultOms) ReturnApplyUpdate(ctx context.Context, in *ReturnApplyUpdateReq, opts ...grpc.CallOption) (*ReturnApplyUpdateResp, error) {
	client := oms.NewOmsClient(m.cli.Conn())
	return client.ReturnApplyUpdate(ctx, in, opts...)
}

// 退货列表
func (m *defaultOms) ReturnApplyList(ctx context.Context, in *ReturnApplyListReq, opts ...grpc.CallOption) (*ReturnApplyListResp, error) {
	client := oms.NewOmsClient(m.cli.Conn())
	return client.ReturnApplyList(ctx, in, opts...)
}

// 删除退货
func (m *defaultOms) ReturnApplyDelete(ctx context.Context, in *ReturnApplyDeleteReq, opts ...grpc.CallOption) (*ReturnApplyDeleteResp, error) {
	client := oms.NewOmsClient(m.cli.Conn())
	return client.ReturnApplyDelete(ctx, in, opts...)
}

// 添加购物车
func (m *defaultOms) CartAdd(ctx context.Context, in *CartAddReq, opts ...grpc.CallOption) (*CartAddResp, error) {
	client := oms.NewOmsClient(m.cli.Conn())
	return client.CartAdd(ctx, in, opts...)
}

// 更新购物车
func (m *defaultOms) CartUpdate(ctx context.Context, in *CartUpdateReq, opts ...grpc.CallOption) (*CartUpdateResp, error) {
	client := oms.NewOmsClient(m.cli.Conn())
	return client.CartUpdate(ctx, in, opts...)
}

// 购物车列表
func (m *defaultOms) CartList(ctx context.Context, in *CartListReq, opts ...grpc.CallOption) (*CartListResp, error) {
	client := oms.NewOmsClient(m.cli.Conn())
	return client.CartList(ctx, in, opts...)
}

// 删除购物车
func (m *defaultOms) CartDelete(ctx context.Context, in *CartDeleteReq, opts ...grpc.CallOption) (*CartDeleteResp, error) {
	client := oms.NewOmsClient(m.cli.Conn())
	return client.CartDelete(ctx, in, opts...)
}
