// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: sms.proto

package sms

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Sms_HomeAdvertiseAdd_FullMethodName    = "/sms.Sms/HomeAdvertiseAdd"
	Sms_HomeAdvertiseList_FullMethodName   = "/sms.Sms/HomeAdvertiseList"
	Sms_HomeAdvertiseUpdate_FullMethodName = "/sms.Sms/HomeAdvertiseUpdate"
	Sms_HomeAdvertiseDelete_FullMethodName = "/sms.Sms/HomeAdvertiseDelete"
	Sms_CouponAdd_FullMethodName           = "/sms.Sms/CouponAdd"
	Sms_CouponUpdate_FullMethodName        = "/sms.Sms/CouponUpdate"
	Sms_CouponDelete_FullMethodName        = "/sms.Sms/CouponDelete"
	Sms_CouponList_FullMethodName          = "/sms.Sms/CouponList"
)

// SmsClient is the client API for Sms service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SmsClient interface {
	// 添加广告
	HomeAdvertiseAdd(ctx context.Context, in *HomeAdvertiseAddReq, opts ...grpc.CallOption) (*HomeAdvertiseAddResp, error)
	// 广告列表
	HomeAdvertiseList(ctx context.Context, in *HomeAdvertiseListReq, opts ...grpc.CallOption) (*HomeAdvertiseListResp, error)
	// 更新广告
	HomeAdvertiseUpdate(ctx context.Context, in *HomeAdvertiseUpdateReq, opts ...grpc.CallOption) (*HomeAdvertiseUpdateResp, error)
	// 删除广告
	HomeAdvertiseDelete(ctx context.Context, in *HomeAdvertiseDeleteReq, opts ...grpc.CallOption) (*HomeAdvertiseDeleteResp, error)
	// 添加优惠券
	CouponAdd(ctx context.Context, in *CouponAddReq, opts ...grpc.CallOption) (*CouponAddResp, error)
	// 更新优惠券
	CouponUpdate(ctx context.Context, in *CouponUpdateReq, opts ...grpc.CallOption) (*CouponUpdateResp, error)
	// 删除优惠券
	CouponDelete(ctx context.Context, in *CouponDeleteReq, opts ...grpc.CallOption) (*CouponDeleteResp, error)
	// 优惠券列表
	CouponList(ctx context.Context, in *CouponListReq, opts ...grpc.CallOption) (*CouponListResp, error)
}

type smsClient struct {
	cc grpc.ClientConnInterface
}

func NewSmsClient(cc grpc.ClientConnInterface) SmsClient {
	return &smsClient{cc}
}

func (c *smsClient) HomeAdvertiseAdd(ctx context.Context, in *HomeAdvertiseAddReq, opts ...grpc.CallOption) (*HomeAdvertiseAddResp, error) {
	out := new(HomeAdvertiseAddResp)
	err := c.cc.Invoke(ctx, Sms_HomeAdvertiseAdd_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smsClient) HomeAdvertiseList(ctx context.Context, in *HomeAdvertiseListReq, opts ...grpc.CallOption) (*HomeAdvertiseListResp, error) {
	out := new(HomeAdvertiseListResp)
	err := c.cc.Invoke(ctx, Sms_HomeAdvertiseList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smsClient) HomeAdvertiseUpdate(ctx context.Context, in *HomeAdvertiseUpdateReq, opts ...grpc.CallOption) (*HomeAdvertiseUpdateResp, error) {
	out := new(HomeAdvertiseUpdateResp)
	err := c.cc.Invoke(ctx, Sms_HomeAdvertiseUpdate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smsClient) HomeAdvertiseDelete(ctx context.Context, in *HomeAdvertiseDeleteReq, opts ...grpc.CallOption) (*HomeAdvertiseDeleteResp, error) {
	out := new(HomeAdvertiseDeleteResp)
	err := c.cc.Invoke(ctx, Sms_HomeAdvertiseDelete_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smsClient) CouponAdd(ctx context.Context, in *CouponAddReq, opts ...grpc.CallOption) (*CouponAddResp, error) {
	out := new(CouponAddResp)
	err := c.cc.Invoke(ctx, Sms_CouponAdd_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smsClient) CouponUpdate(ctx context.Context, in *CouponUpdateReq, opts ...grpc.CallOption) (*CouponUpdateResp, error) {
	out := new(CouponUpdateResp)
	err := c.cc.Invoke(ctx, Sms_CouponUpdate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smsClient) CouponDelete(ctx context.Context, in *CouponDeleteReq, opts ...grpc.CallOption) (*CouponDeleteResp, error) {
	out := new(CouponDeleteResp)
	err := c.cc.Invoke(ctx, Sms_CouponDelete_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smsClient) CouponList(ctx context.Context, in *CouponListReq, opts ...grpc.CallOption) (*CouponListResp, error) {
	out := new(CouponListResp)
	err := c.cc.Invoke(ctx, Sms_CouponList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SmsServer is the server API for Sms service.
// All implementations must embed UnimplementedSmsServer
// for forward compatibility
type SmsServer interface {
	// 添加广告
	HomeAdvertiseAdd(context.Context, *HomeAdvertiseAddReq) (*HomeAdvertiseAddResp, error)
	// 广告列表
	HomeAdvertiseList(context.Context, *HomeAdvertiseListReq) (*HomeAdvertiseListResp, error)
	// 更新广告
	HomeAdvertiseUpdate(context.Context, *HomeAdvertiseUpdateReq) (*HomeAdvertiseUpdateResp, error)
	// 删除广告
	HomeAdvertiseDelete(context.Context, *HomeAdvertiseDeleteReq) (*HomeAdvertiseDeleteResp, error)
	// 添加优惠券
	CouponAdd(context.Context, *CouponAddReq) (*CouponAddResp, error)
	// 更新优惠券
	CouponUpdate(context.Context, *CouponUpdateReq) (*CouponUpdateResp, error)
	// 删除优惠券
	CouponDelete(context.Context, *CouponDeleteReq) (*CouponDeleteResp, error)
	// 优惠券列表
	CouponList(context.Context, *CouponListReq) (*CouponListResp, error)
	mustEmbedUnimplementedSmsServer()
}

// UnimplementedSmsServer must be embedded to have forward compatible implementations.
type UnimplementedSmsServer struct {
}

func (UnimplementedSmsServer) HomeAdvertiseAdd(context.Context, *HomeAdvertiseAddReq) (*HomeAdvertiseAddResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HomeAdvertiseAdd not implemented")
}
func (UnimplementedSmsServer) HomeAdvertiseList(context.Context, *HomeAdvertiseListReq) (*HomeAdvertiseListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HomeAdvertiseList not implemented")
}
func (UnimplementedSmsServer) HomeAdvertiseUpdate(context.Context, *HomeAdvertiseUpdateReq) (*HomeAdvertiseUpdateResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HomeAdvertiseUpdate not implemented")
}
func (UnimplementedSmsServer) HomeAdvertiseDelete(context.Context, *HomeAdvertiseDeleteReq) (*HomeAdvertiseDeleteResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HomeAdvertiseDelete not implemented")
}
func (UnimplementedSmsServer) CouponAdd(context.Context, *CouponAddReq) (*CouponAddResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CouponAdd not implemented")
}
func (UnimplementedSmsServer) CouponUpdate(context.Context, *CouponUpdateReq) (*CouponUpdateResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CouponUpdate not implemented")
}
func (UnimplementedSmsServer) CouponDelete(context.Context, *CouponDeleteReq) (*CouponDeleteResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CouponDelete not implemented")
}
func (UnimplementedSmsServer) CouponList(context.Context, *CouponListReq) (*CouponListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CouponList not implemented")
}
func (UnimplementedSmsServer) mustEmbedUnimplementedSmsServer() {}

// UnsafeSmsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SmsServer will
// result in compilation errors.
type UnsafeSmsServer interface {
	mustEmbedUnimplementedSmsServer()
}

func RegisterSmsServer(s grpc.ServiceRegistrar, srv SmsServer) {
	s.RegisterService(&Sms_ServiceDesc, srv)
}

func _Sms_HomeAdvertiseAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HomeAdvertiseAddReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmsServer).HomeAdvertiseAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sms_HomeAdvertiseAdd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmsServer).HomeAdvertiseAdd(ctx, req.(*HomeAdvertiseAddReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sms_HomeAdvertiseList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HomeAdvertiseListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmsServer).HomeAdvertiseList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sms_HomeAdvertiseList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmsServer).HomeAdvertiseList(ctx, req.(*HomeAdvertiseListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sms_HomeAdvertiseUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HomeAdvertiseUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmsServer).HomeAdvertiseUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sms_HomeAdvertiseUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmsServer).HomeAdvertiseUpdate(ctx, req.(*HomeAdvertiseUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sms_HomeAdvertiseDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HomeAdvertiseDeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmsServer).HomeAdvertiseDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sms_HomeAdvertiseDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmsServer).HomeAdvertiseDelete(ctx, req.(*HomeAdvertiseDeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sms_CouponAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CouponAddReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmsServer).CouponAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sms_CouponAdd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmsServer).CouponAdd(ctx, req.(*CouponAddReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sms_CouponUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CouponUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmsServer).CouponUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sms_CouponUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmsServer).CouponUpdate(ctx, req.(*CouponUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sms_CouponDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CouponDeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmsServer).CouponDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sms_CouponDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmsServer).CouponDelete(ctx, req.(*CouponDeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sms_CouponList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CouponListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmsServer).CouponList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sms_CouponList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmsServer).CouponList(ctx, req.(*CouponListReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Sms_ServiceDesc is the grpc.ServiceDesc for Sms service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Sms_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sms.Sms",
	HandlerType: (*SmsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HomeAdvertiseAdd",
			Handler:    _Sms_HomeAdvertiseAdd_Handler,
		},
		{
			MethodName: "HomeAdvertiseList",
			Handler:    _Sms_HomeAdvertiseList_Handler,
		},
		{
			MethodName: "HomeAdvertiseUpdate",
			Handler:    _Sms_HomeAdvertiseUpdate_Handler,
		},
		{
			MethodName: "HomeAdvertiseDelete",
			Handler:    _Sms_HomeAdvertiseDelete_Handler,
		},
		{
			MethodName: "CouponAdd",
			Handler:    _Sms_CouponAdd_Handler,
		},
		{
			MethodName: "CouponUpdate",
			Handler:    _Sms_CouponUpdate_Handler,
		},
		{
			MethodName: "CouponDelete",
			Handler:    _Sms_CouponDelete_Handler,
		},
		{
			MethodName: "CouponList",
			Handler:    _Sms_CouponList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sms.proto",
}
