// Code generated by goctl. DO NOT EDIT.
package types

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
	Data    string `json:"data"`
}

type UserInfoResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
	Data    Data   `json:"data"`
}

type Data struct {
	UserInfo UserInfo `json:"userInfo"`
	Routes   []string `json:"routes"`
	Roles    []string `json:"roles"`
	Buttons  []string `json:"buttons"`
}

type UserInfo struct {
	ID       int64  `json:"id"`
	Username string `json:"username"`
	NickName string `json:"nickname"`
	Phone    string `json:"phone"`
	Gander   string `json:"gender"`
	Avatar   string `json:"avatar"`
	Email    string `json:"email"`
	Status   string `json:"status"`
	CreateAt string `json:"creat_at"`
	UpdateAt string `json:"update_at"`
	CreateBy string `json:"creat_by"`
	UpdateBy string `json:"update_by"`
}

type AddUserReq struct {
	Username string  `json:"username"`
	Phone    string  `json:"phone"`
	Nickname string  `json:"nickname"`
	Gender   string  `json:"gender"`
	Email    string  `json:"email"`
	Status   string  `json:"status"`
	RoleID   []int64 `json:"roleId,optional"`
}

type AddUserResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type UpdateUserReq struct {
	ID       int64   `json:"id"`
	Username string  `json:"username,optional"`
	Phone    string  `json:"phone,optional"`
	Nickname string  `json:"nickname,optional"`
	Gender   string  `json:"gender,optional"`
	Status   string  `json:"status,optional"`
	Email    string  `json:"email,optional"`
	RoleID   []int64 `json:"roleId,optional"`
}

type UpdateUserResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type DeleteUserReq struct {
	Ids []int64 `json:"ids"`
}

type DeleteUserResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type ListUserReq struct {
	Current  int64  `form:"current"`
	PageSize int64  `form:"pageSize"`
	Nickname string `form:"nickname,optional"`
	Phone    string `form:"phone,optional"`
	Username string `form:"username,optional"`
	Status   string `form:"status,optional"`
	Gander   string `form:"gender,optional"`
}

type User struct {
	ID       int64    `json:"id"`
	Username string   `json:"username"`
	NickName string   `json:"nickname"`
	Phone    string   `json:"phone"`
	Gander   string   `json:"gender"`
	Avatar   string   `json:"avatar"`
	Email    string   `json:"email"`
	Status   string   `json:"status"`
	CreateAt string   `json:"creat_at"`
	UpdateAt string   `json:"update_at"`
	CreateBy string   `json:"creat_by"`
	UpdateBy string   `json:"update_by"`
	RoleName []string `json:"roleName"`
}

type ListUserResp struct {
	Code    int64   `json:"code"`
	Message string  `json:"message"`
	Data    []*User `json:"data"`
	Total   int64   `json:"total"`
}

type UpdatePasswordReq struct {
	OldPassword string `json:"oldPassword"`
	NewPassword string `json:"newPassword"`
}

type UpdatePasswordResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type RestartPasswordReq struct {
	ID int64 `json:"id"`
}

type RestartPasswordResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type ListLoginLogReq struct {
	Current  int64  `form:"current,default=1"`
	PageSize int64  `form:"pageSize,default=20"`
	Username string `form:"username,optional"`
	Status   string `form:"status,optional"` // 登录状态（online:在线，登录初始状态，方便统计在线人数；login:退出登录后将online置为login；logout:退出登录）
}

type ListLoginLogData struct {
	Id         int64  `json:"id"` // 编号
	UserId     int64  `json:"userId"`
	Status     string `json:"status"`     // 登录状态（online:在线，登录初始状态，方便统计在线人数；login:退出登录后将online置为login；logout:退出登录）
	Ip         string `json:"ip"`         // IP地址
	CreateTime string `json:"createTime"` // 创建时间
	Avatar     string `json:"avatar"`
	Username   string `json:"username"`
}

type ListLoginLogResp struct {
	Code    int64               `json:"code"`
	Message string              `json:"message"`
	Total   int64               `json:"total"`
	Data    []*ListLoginLogData `json:"data"`
}

type DeleteLoginLogReq struct {
	Ids []int64 `json:"ids"`
}

type DeleteLoginLogResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type AddPlaceReq struct {
	Name      string `json:"name"`
	Place     string `json:"place"`
	Status    string `json:"status"`
	Pic       string `json:"pic"`
	Phone     string `json:"phone"`
	Principal string `json:"principal"`
}

type AddPlaceResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type UpdatePlaceReq struct {
	Id        int64  `json:"id"`
	Name      string `json:"name"`
	Place     string `json:"place"`
	Status    string `json:"status"`
	Pic       string `json:"pic"`
	Phone     string `json:"phone"`
	Principal string `json:"principal"`
}

type UpdatePlaceResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type DeletePlaceReq struct {
	Ids []int64 `json:"ids"`
}

type DeletePlaceResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type ListPlaceReq struct {
	Current  int64  `form:"current,default=1"`
	PageSize int64  `form:"pageSize,default=20"`
	Name     string `form:"name,optional "`
	Place    string `form:"place,optional"`
	Phone    string `form:"phone,optional"`
}

type ListPlaceData struct {
	Id        int64  `json:"id"`
	Name      string `json:"name"`
	Place     string `json:"place"`
	Status    string `json:"status"`
	Pic       string `json:"pic"`
	Phone     string `json:"phone"`
	Principal string `json:"principal"`
}

type ListPlaceResp struct {
	Code    int64            `json:"code"`
	Message string           `json:"message"`
	Total   int64            `json:"total"`
	Data    []*ListPlaceData `json:"data"`
}

type AddRoleReq struct {
	Name   string `json:"name"`
	Remark string `json:"remark,optional"`
}

type AddRoleResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type UpdateRoleReq struct {
	Id     int64  `json:"id"`
	Name   string `json:"name"`
	Remark string `json:"remark"`
}

type UpdateRoleResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type DeleteRoleReq struct {
	Ids []int64 `json:"ids"`
}

type DeleteRoleResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type ListRoleReq struct {
	Current  int64  `form:"current,optional"`
	PageSize int64  `form:"pageSize,optional"`
	Name     string `form:"name,optional"`
}

type ListRoleData struct {
	Id       int64  `json:"id"`        // 编号
	Name     string `json:"name"`      // 角色名称
	Remark   string `json:"remark"`    // 备注
	CreateBy string `json:"create_by"` // 创建人
	CreateAt string `json:"create_at"` // 创建时间
	UpdateBy string `json:"update_by"` // 更新人
	UpdateAt string `json:"update_at"` // 更新时间
}

type ListRoleResp struct {
	Code    int64           `json:"code"`
	Message string          `json:"message"`
	Total   int64           `json:"total"`
	Data    []*ListRoleData `json:"data"`
}

type RoleByUserListReq struct {
	UserID int64 `json:"userID"`
}

type RoleByUserListResp struct {
	Code    int64           `json:"code"`
	Message string          `json:"message"`
	Data    []*ListRoleData `json:"data"`
}

type RoleMenuReq struct {
	Id int64 `json:"id,optional"`
}

type RoleMenuResp struct {
	Data    []int64 `json:"data"`
	Code    int64   `json:"code"`
	Message string  `json:"message"`
}

type UpdateRoleMenuReq struct {
	RoleId  int64   `json:"roleId"`
	MenuIds []int64 `json:"menuIds"`
}

type UpdateRoleMenuResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type AddMenuReq struct {
	Name     string `json:"name"`              // 菜单名称
	ParentId int64  `json:"parentId,optional"` // 父菜单ID，一级菜单为0
	Url      string `json:"url,optional"`      // 菜单URL,类型：1.普通页面（如用户管理， /sysmodel/user） 2.嵌套完整外部页面，以http(s)开头的链接 3.嵌套服务器页面，使用iframe:前缀+目标URL(如SQL监控， iframe:/druid/login.html, iframe:前缀会替换成服务器地址)
	Remark   string `json:"remark,optional"`
	Type     string `json:"type,optional"`     // 类型   0：目录   1：菜单   2：按钮
	Icon     string `json:"icon,optional"`     // 菜单图标
	OrderNum int64  `json:"orderNum,optional"` // 排序
	TAG      string `json:"tag"`
}

type AddMenuResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type ListMenuReq struct {
}

type ListMenuData struct {
	Id       int64          `json:"id"`       // 编号
	Name     string         `json:"name"`     // 菜单名称
	ParentId int64          `json:"parentId"` // 父菜单ID，一级菜单为0
	Url      string         `json:"url"`      // 菜单URL,类型：1.普通页面（如用户管理， /sysmodel/user） 2.嵌套完整外部页面，以http(s)开头的链接 3.嵌套服务器页面，使用iframe:前缀+目标URL(如SQL监控， iframe:/druid/login.html, iframe:前缀会替换成服务器地址)
	Remark   string         `json:"remark"`   // 授权(多个用逗号分隔，如：sysmodel:user:add,sysmodel:user:edit)
	Type     string         `json:"type"`     // 类型   0：目录   1：菜单   2：按钮
	Icon     string         `json:"icon"`     // 菜单图标
	OrderNum int64          `json:"orderNum"` // 排序
	TAG      string         `json:"tag"`
	Children []ListMenuData `json:"children"`
}

type ListMenuResp struct {
	Code    int64          `json:"code"`
	Message string         `json:"message"`
	Data    []ListMenuData `json:"data"`
}

type UpdateMenuReq struct {
	Id       int64  `json:"id"`                 // 编号
	Name     string `json:"name"`               // 菜单名称
	ParentId int64  `json:"parentId,default=0"` // 父菜单ID，一级菜单为0
	Url      string `json:"url,optional"`       // 菜单URL,类型：1.普通页面（如用户管理， /sysmodel/user） 2.嵌套完整外部页面，以http(s)开头的链接 3.嵌套服务器页面，使用iframe:前缀+目标URL(如SQL监控， iframe:/druid/login.html, iframe:前缀会替换成服务器地址)
	Remark   string `json:"remark,optional"`    // 授权(多个用逗号分隔，如：sysmodel:user:add,sysmodel:user:edit)
	Type     string `json:"type,optional"`      // 类型   0：目录   1：菜单   2：按钮
	Icon     string `json:"icon,optional"`      // 菜单图标
	OrderNum int64  `json:"orderNum,optional"`  // 排序
	TAG      string `json:"tag"`
}

type UpdateMenuResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type DeleteMenuReq struct {
	Ids []int64 `json:"ids"`
}

type DeleteMenuResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type ListSysLogReq struct {
	PageNum  int64  `form:"pageNum,default=1"`
	PageSize int64  `form:"pageSize,default=20"`
	Method   string `form:"method,optional"` // 请求方法
}

type ListSysLogData struct {
	Id         int64  `json:"id"`        // 编号
	UserId     int64  `json:"userId"`    // 编号
	Operation  string `json:"operation"` // 用户操作
	Method     string `json:"method"`    // 请求方法
	Params     string `json:"params"`    // 请求参数
	Time       int64  `json:"time"`      // 执行时长(毫秒)
	Ip         string `json:"ip"`        // IP地址
	Avatar     string `json:"avatar"`
	CreateTime string `json:"createTime"` // 创建时间
	Username   string `json:"username"`   // 创建时间
}

type ListSysLogResp struct {
	Code     int64             `json:"code"`
	Message  string            `json:"message"`
	PageNum  int64             `json:"pageNum,default=1"`
	Data     []*ListSysLogData `json:"data"`
	PageSize int64             `json:"pageSize,default=20"`
	Total    int64             `json:"total"`
}

type DeleteSysLogReq struct {
	Ids []int64 `json:"ids"`
}

type DeleteSysLogResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type UploadResp struct {
	Data string `json:"data"`
}

type AddCategoryReq struct {
	ParentId    int64  `json:"parentId"` // 上级分类的编号：0表示一级分类
	Name        string `json:"name"`
	Level       string `json:"level"`      // 分类级别：1->1级；2->2级
	NavStatus   string `json:"navStatus"`  // 是否显示在导航栏：0->不显示；1->显示
	ShowStatus  string `json:"showStatus"` // 显示状态：0->不显示；1->显示
	ProductUnit string `json:"productUnit"`
	Sort        int64  `json:"sort"`
	Icon        string `json:"icon"` // 图标
	Keywords    string `json:"keywords,optional"`
	Description string `json:"description,optional"` // 描述
}

type AddCategoryResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type ListCategoryReq struct {
	Current  int64  `json:"current,default=1"`
	PageSize int64  `json:"pageSize,default=20"`
	Name     string `json:"name,optional"`
	ParentId int64  `json:"parentId,default=2"` // 上级分类的编号：0表示一级分类
}

type ListCategoryData struct {
	Id           int64              `json:"id"`
	ParentId     int64              `json:"parentId"` // 上级分类的编号：0表示一级分类
	Name         string             `json:"name"`
	Level        string             `json:"level"` // 分类级别：0->1级；1->2级
	ProductCount int64              `json:"productCount"`
	ProductUnit  string             `json:"productUnit"`
	NavStatus    string             `json:"navStatus"`  // 是否显示在导航栏：0->不显示；1->显示
	ShowStatus   string             `json:"showStatus"` // 显示状态：0->不显示；1->显示
	Sort         int64              `json:"sort"`
	Icon         string             `json:"icon"` // 图标
	Keywords     string             `json:"keywords"`
	Description  string             `json:"description"` // 描述
	Children     []ListCategoryData `json:"children"`
}

type ListCategoryResp struct {
	Code    int64              `json:"code"`
	Message string             `json:"message"`
	Data    []ListCategoryData `json:"data"`
	Total   int64              `json:"total"`
}

type UpdateCategoryReq struct {
	Id           int64  `json:"id"`
	ParentId     int64  `json:"parentId"` // 上级分类的编号：0表示一级分类
	Name         string `json:"name"`
	Level        string `json:"level"` // 分类级别：0->1级；1->2级
	ProductCount int64  `json:"productCount,optional"`
	ProductUnit  string `json:"productUnit"`
	NavStatus    string `json:"navStatus"`  // 是否显示在导航栏：0->不显示；1->显示
	ShowStatus   string `json:"showStatus"` // 显示状态：0->不显示；1->显示
	Sort         int64  `json:"sort"`
	Icon         string `json:"icon"` // 图标
	Keywords     string `json:"keywords"`
	Description  string `json:"description"` // 描述
}

type UpdateCategoryResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type DeleteCategoryReq struct {
	Ids []int64 `json:"ids"`
}

type DeleteCategoryResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type AddAttributeReq struct {
	CategoryId int64    `json:"CategoryId"` // 属性分类id
	Name       string   `json:"name"`
	Type       string   `json:"type"`
	Value      []string `json:"value"`
}

type AddAttributeResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type ListAttributeReq struct {
	Current    int64  `json:"current,default=1"`
	PageSize   int64  `json:"pageSize,default=20"`
	Name       string `json:"name,optional"`
	Type       string `json:"type,default=2"`
	CategoryId int64  `json:"categoryId,default=0"`
}

type ListAttributeData struct {
	Id             int64            `json:"id"`
	CategoryId     int64            `json:"categoryId"`
	Name           string           `json:"name"`
	Type           string           `json:"type"`
	AttributeValue []AttributeValue `json:"attributeValue"`
}

type AttributeValue struct {
	Id          int64  `json:"id"`
	Name        string `json:"name"`
	AttributeID int64  `json:"attributeID"`
}

type ListAttributeResp struct {
	Code    int64               `json:"code"`
	Message string              `json:"message"`
	Data    []ListAttributeData `json:"data"`
	Total   int64               `json:"total"`
}

type UpdateAttributeReq struct {
	Id          int64         `json:"id"`
	CategoryId  int64         `json:"CategoryId"`
	Name        string        `json:"name"`
	Type        string        `json:"type"`
	UpdateValue []UpdateValue `json:"updateValue"`
}

type UpdateValue struct {
	Id    int64  `json:"id"`
	Value string `json:"value"`
}

type UpdateAttributeResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type DeleteAttributeReq struct {
	Ids []int64 `json:"ids"`
}

type DeleteAttributeResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type AddProductReq struct {
	CategoryID    int64   `json:"categoryId"`
	Name          string  `json:"name"`
	Pic           string  `json:"pic,optional"`
	ProductSn     string  `json:"productSn"`
	SubTitle      string  `json:"subTitle,optional"`
	Description   string  `json:"description,optional"`
	OriginalPrice float64 `json:"originalPrice,optional"`
	Stock         int64   `json:"stock,optional"`
	Unit          string  `json:"unit,optional"`
	Sale          int64   `json:"sale,optional"`
	Price         float64 `json:"price,optional"`
	AttributeID   []int64 `json:"attributeID,optional"`
}

type AddProductResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type ListProductReq struct {
	Current  int64 `json:"current,default=1"`
	PageSize int64 `json:"pageSize,default=20"`
}

type ListProductData struct {
	Id            int64   `json:"id"`
	CategoryID    int64   `json:"categoryId"`
	Name          string  `json:"name"`
	Pic           string  `json:"pic,optional"`
	ProductSn     string  `json:"productSn"`
	SubTitle      string  `json:"subTitle,optional"`
	Description   string  `json:"description,optional"`
	OriginalPrice float64 `json:"originalPrice,optional"`
	Stock         int64   `json:"stock,optional"`
	Unit          string  `json:"unit,optional"`
	Sale          int64   `json:"sale,optional,default=0"`
	Price         float64 `json:"price,optional"`
}

type ListProductResp struct {
	Code    int64             `json:"code"`
	Message string            `json:"message"`
	Data    []ListProductData `json:"data"`
	Total   int64             `json:"total"`
}

type UpdateProductReq struct {
	Id            int64   `json:"id"`
	CategoryID    int64   `json:"categoryId"`
	Name          string  `json:"name"`
	Pic           string  `json:"pic,optional"`
	ProductSn     string  `json:"productSn"`
	SubTitle      string  `json:"subTitle,optional"`
	Description   string  `json:"description,optional"`
	OriginalPrice float64 `json:"originalPrice,optional"`
	Stock         int64   `json:"stock,optional"`
	Unit          string  `json:"unit,optional"`
	Sale          int64   `json:"sale,optional,default=0"`
	Price         float64 `json:"price,optional"`
	AttributeID   []int64 `json:"attributeID,optional"`
}

type UpdateProductResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type DeleteProductReq struct {
	Ids []int64 `json:"ids"`
}

type DeleteProductResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}
