// Code generated by goctl. DO NOT EDIT.
// Source: oms.proto

package server

import (
	"context"

	"SimplePick-Mall-Server/service/oms/rpc/internal/logic"
	"SimplePick-Mall-Server/service/oms/rpc/internal/svc"
	"SimplePick-Mall-Server/service/oms/rpc/oms"
)

type OmsServer struct {
	svcCtx *svc.ServiceContext
	oms.UnimplementedOmsServer
}

func NewOmsServer(svcCtx *svc.ServiceContext) *OmsServer {
	return &OmsServer{
		svcCtx: svcCtx,
	}
}

// 添加订单
func (s *OmsServer) OrderAdd(ctx context.Context, in *oms.OrderAddReq) (*oms.OrderAddResp, error) {
	l := logic.NewOrderAddLogic(ctx, s.svcCtx)
	return l.OrderAdd(in)
}

// 订单列表
func (s *OmsServer) OrderList(ctx context.Context, in *oms.OrderListReq) (*oms.OrderListResp, error) {
	l := logic.NewOrderListLogic(ctx, s.svcCtx)
	return l.OrderList(in)
}

// 更新订单
func (s *OmsServer) OrderUpdate(ctx context.Context, in *oms.OrderUpdateReq) (*oms.OrderUpdateResp, error) {
	l := logic.NewOrderUpdateLogic(ctx, s.svcCtx)
	return l.OrderUpdate(in)
}

// 删除订单
func (s *OmsServer) OrderDelete(ctx context.Context, in *oms.OrderDeleteReq) (*oms.OrderDeleteResp, error) {
	l := logic.NewOrderDeleteLogic(ctx, s.svcCtx)
	return l.OrderDelete(in)
}

// 订单详情
func (s *OmsServer) OrderInfo(ctx context.Context, in *oms.OrderInfoReq) (*oms.OrderInfoResp, error) {
	l := logic.NewOrderInfoLogic(ctx, s.svcCtx)
	return l.OrderInfo(in)
}

// 添加退货原因
func (s *OmsServer) ReturnReasonAdd(ctx context.Context, in *oms.ReturnReasonAddReq) (*oms.ReturnReasonAddResp, error) {
	l := logic.NewReturnReasonAddLogic(ctx, s.svcCtx)
	return l.ReturnReasonAdd(in)
}

// 更新退货原因
func (s *OmsServer) ReturnReasonUpdate(ctx context.Context, in *oms.ReturnReasonUpdateReq) (*oms.ReturnReasonUpdateResp, error) {
	l := logic.NewReturnReasonUpdateLogic(ctx, s.svcCtx)
	return l.ReturnReasonUpdate(in)
}

// 退货原因列表
func (s *OmsServer) ReturnReasonList(ctx context.Context, in *oms.ReturnReasonListReq) (*oms.ReturnReasonListResp, error) {
	l := logic.NewReturnReasonListLogic(ctx, s.svcCtx)
	return l.ReturnReasonList(in)
}

// 删除退货原因
func (s *OmsServer) ReturnReasonDelete(ctx context.Context, in *oms.ReturnReasonDeleteReq) (*oms.ReturnReasonDeleteResp, error) {
	l := logic.NewReturnReasonDeleteLogic(ctx, s.svcCtx)
	return l.ReturnReasonDelete(in)
}

// 添加退货
func (s *OmsServer) ReturnApplyAdd(ctx context.Context, in *oms.ReturnApplyAddReq) (*oms.ReturnApplyAddResp, error) {
	l := logic.NewReturnApplyAddLogic(ctx, s.svcCtx)
	return l.ReturnApplyAdd(in)
}

// 更新退货
func (s *OmsServer) ReturnApplyUpdate(ctx context.Context, in *oms.ReturnApplyUpdateReq) (*oms.ReturnApplyUpdateResp, error) {
	l := logic.NewReturnApplyUpdateLogic(ctx, s.svcCtx)
	return l.ReturnApplyUpdate(in)
}

// 退货列表
func (s *OmsServer) ReturnApplyList(ctx context.Context, in *oms.ReturnApplyListReq) (*oms.ReturnApplyListResp, error) {
	l := logic.NewReturnApplyListLogic(ctx, s.svcCtx)
	return l.ReturnApplyList(in)
}

// 删除退货
func (s *OmsServer) ReturnApplyDelete(ctx context.Context, in *oms.ReturnApplyDeleteReq) (*oms.ReturnApplyDeleteResp, error) {
	l := logic.NewReturnApplyDeleteLogic(ctx, s.svcCtx)
	return l.ReturnApplyDelete(in)
}

// 添加购物车
func (s *OmsServer) CartAdd(ctx context.Context, in *oms.CartAddReq) (*oms.CartAddResp, error) {
	l := logic.NewCartAddLogic(ctx, s.svcCtx)
	return l.CartAdd(in)
}

// 更新购物车
func (s *OmsServer) CartUpdate(ctx context.Context, in *oms.CartUpdateReq) (*oms.CartUpdateResp, error) {
	l := logic.NewCartUpdateLogic(ctx, s.svcCtx)
	return l.CartUpdate(in)
}

// 购物车列表
func (s *OmsServer) CartList(ctx context.Context, in *oms.CartListReq) (*oms.CartListResp, error) {
	l := logic.NewCartListLogic(ctx, s.svcCtx)
	return l.CartList(in)
}

// 删除购物车
func (s *OmsServer) CartDelete(ctx context.Context, in *oms.CartDeleteReq) (*oms.CartDeleteResp, error) {
	l := logic.NewCartDeleteLogic(ctx, s.svcCtx)
	return l.CartDelete(in)
}
