// Code generated by goctl. DO NOT EDIT.
// Source: oms.proto

package server

import (
	"context"

	"SimplePick-Mall-Server/service/oms/rpc/internal/logic"
	"SimplePick-Mall-Server/service/oms/rpc/internal/svc"
	"SimplePick-Mall-Server/service/oms/rpc/oms"
)

type OmsServer struct {
	svcCtx *svc.ServiceContext
	oms.UnimplementedOmsServer
}

func NewOmsServer(svcCtx *svc.ServiceContext) *OmsServer {
	return &OmsServer{
		svcCtx: svcCtx,
	}
}

// 添加订单
func (s *OmsServer) OrderAdd(ctx context.Context, in *oms.OrderAddReq) (*oms.OrderAddResp, error) {
	l := logic.NewOrderAddLogic(ctx, s.svcCtx)
	return l.OrderAdd(in)
}

// 订单列表
func (s *OmsServer) OrderList(ctx context.Context, in *oms.OrderListReq) (*oms.OrderListResp, error) {
	l := logic.NewOrderListLogic(ctx, s.svcCtx)
	return l.OrderList(in)
}

// 更新订单
func (s *OmsServer) OrderUpdate(ctx context.Context, in *oms.OrderUpdateReq) (*oms.OrderUpdateResp, error) {
	l := logic.NewOrderUpdateLogic(ctx, s.svcCtx)
	return l.OrderUpdate(in)
}

// 删除订单
func (s *OmsServer) OrderDelete(ctx context.Context, in *oms.OrderDeleteReq) (*oms.OrderDeleteResp, error) {
	l := logic.NewOrderDeleteLogic(ctx, s.svcCtx)
	return l.OrderDelete(in)
}

// 订单详情
func (s *OmsServer) OrderInfo(ctx context.Context, in *oms.OrderInfoReq) (*oms.OrderInfoResp, error) {
	l := logic.NewOrderInfoLogic(ctx, s.svcCtx)
	return l.OrderInfo(in)
}
